<?php
if ( ! defined( 'WPINC' ) ) {die;
}
$wf_admin_img_path = WF_PKLIST_PLUGIN_URL . 'admin/images';
$wf_admin_img_path_os = WF_PKLIST_PLUGIN_URL . 'admin/images/other_solutions';
$premium_ext_lists = array(
    'accounting' => array(
        'domain_name' => __('Premium extensions',"print-invoices-packing-slip-labels-for-woocommerce"),
        'domain_caption' => __("Automatically generate professional WooCommerce order-related documents for all your orders","print-invoices-packing-slip-labels-for-woocommerce"),
        'domain_logo' => $wf_admin_img_path.'/pro_addons/pro_crown.png',
        'plugins' => array(
            'wt_ipc_addon' => array(
                'file_path' => 'wt-woocommerce-invoice-addon/wt-woocommerce-invoice-addon.php',
                'logo' => $wf_admin_img_path.'/wt_ipc_logo.png',
                'title' => __("WooCommerce PDF Invoices, Packing Slips and Credit Notes plugin","print-invoices-packing-slip-labels-for-woocommerce"),
                'page_link' => 'https://www.webtoffee.com/product/woocommerce-pdf-invoices-packing-slips/?utm_source=other_solution_page&utm_medium=free_plugin&utm_campaign=PDF_invoice',
                'features_list' => array(
                    __("Auto-generate invoices, packing slips, and credit notes","print-invoices-packing-slip-labels-for-woocommerce"),
                    __("Show payment link on invoice","print-invoices-packing-slip-labels-for-woocommerce"),
                    __("Add ‘Pay Later’ option at checkout","print-invoices-packing-slip-labels-for-woocommerce"),
                    __("Attach documents to selected order status emails","print-invoices-packing-slip-labels-for-woocommerce"),
                    __("Enable customers to print invoices & packing slips","print-invoices-packing-slip-labels-for-woocommerce"),
                    __("Customize document layout & properties","print-invoices-packing-slip-labels-for-woocommerce"),
                    __("Show product variation data","print-invoices-packing-slip-labels-for-woocommerce"),
                    __("Add custom data to documents","print-invoices-packing-slip-labels-for-woocommerce"),
                    __("Multiple display options for bundle products","print-invoices-packing-slip-labels-for-woocommerce"),
                    __("Group products by ‘Category’","print-invoices-packing-slip-labels-for-woocommerce"),
                    __("Verified compatibility with major plugins","print-invoices-packing-slip-labels-for-woocommerce"),
                    __("Multilingual support","print-invoices-packing-slip-labels-for-woocommerce"),
                ),
            ),
            'wt_sdd_addon' => array(
                'file_path' => 'wt-woocommerce-shippinglabel-addon/wt-woocommerce-shippinglabel-addon.php',
                'logo' => $wf_admin_img_path.'/wt_sdd_logo.png',
                'title' => __("WooCommerce Shipping labels, Dispatch labels and Delivery Notes plugin","print-invoices-packing-slip-labels-for-woocommerce"),
                'page_link' => 'https://www.webtoffee.com/product/woocommerce-shipping-labels-delivery-notes/?utm_source=other_solution_page&utm_medium=free_plugin&utm_campaign=Shipping_Label',
                'features_list' => array(
                    __("Create delivery notes, shipping & dispatch labels","print-invoices-packing-slip-labels-for-woocommerce"),
                    __("Enable customers to print the documents from order emails","print-invoices-packing-slip-labels-for-woocommerce"), 
                    __("Customize shipping label size","print-invoices-packing-slip-labels-for-woocommerce"),
                    __("Add multiple shipping labels on one page","print-invoices-packing-slip-labels-for-woocommerce"),
                    __("Show product variation data","print-invoices-packing-slip-labels-for-woocommerce"), 
                    __("Add extra product & order data fields","print-invoices-packing-slip-labels-for-woocommerce"),
                    __("Pre-built layouts & customizable templates","print-invoices-packing-slip-labels-for-woocommerce"), 
                    __("Group products by ‘Category’","print-invoices-packing-slip-labels-for-woocommerce"),
                    __("Sort products based on Name or SKU","print-invoices-packing-slip-labels-for-woocommerce"),
                    __("Multilingual support","print-invoices-packing-slip-labels-for-woocommerce"),
                ),
            ),
            'wt_pl_addon' => array(
                'file_path' => 'wt-woocommerce-picklist-addon/wt-woocommerce-picklist-addon.php',
                'logo' => $wf_admin_img_path.'/wt_pl_logo.png',
                'title' => __("WooCommerce Picklists plugin","print-invoices-packing-slip-labels-for-woocommerce"),
                'page_link' => 'https://www.webtoffee.com/product/woocommerce-picklist/?utm_source=other_solution_page&utm_medium=free_plugin&utm_campaign=Picklist',
                'features_list' => array(
                    __("Bulk print picklists from the admin order page","print-invoices-packing-slip-labels-for-woocommerce"),
                    __("Automatically email picklists based on order status","print-invoices-packing-slip-labels-for-woocommerce"),
                    __("Create or customize picklist templates","print-invoices-packing-slip-labels-for-woocommerce"),
                    __("Show product variation data","print-invoices-packing-slip-labels-for-woocommerce"),
                    __("Group products in picklist by order/category","print-invoices-packing-slip-labels-for-woocommerce"), 
                    __("Add product meta fields & attributes","print-invoices-packing-slip-labels-for-woocommerce"), 
                    __("Exclude virtual products from picklists","print-invoices-packing-slip-labels-for-woocommerce"),
                    __("Multilingual support","print-invoices-packing-slip-labels-for-woocommerce"),
                ),
            ),
            'wt_al_addon' => array(
                'file_path' => 'wt-woocommerce-addresslabel-addon/wt-woocommerce-addresslabel-addon.php',
                'logo' => $wf_admin_img_path.'/wt_al_logo.png',
                'title' => __("WooCommerce Address Labels plugin","print-invoices-packing-slip-labels-for-woocommerce"),
                'page_link' => 'https://www.webtoffee.com/product/woocommerce-address-label/?utm_source=other_solution_page&utm_medium=free_plugin&utm_campaign=Address_Label',
                'features_list' => array(
                    __("Generate ‘Shipping Address’, ‘Billing Address’, ‘From Address’, and ‘Return Address’ labels","print-invoices-packing-slip-labels-for-woocommerce"),
                    __("Customize label sizes","print-invoices-packing-slip-labels-for-woocommerce"),
                    __("Bulk print address labels","print-invoices-packing-slip-labels-for-woocommerce"),
                    __("Offers built-in label templates","print-invoices-packing-slip-labels-for-woocommerce"),
                    __("Change address label layout","print-invoices-packing-slip-labels-for-woocommerce"),
                    __("Multilingual support","print-invoices-packing-slip-labels-for-woocommerce"),
                ),
            ), 
            'wt_pi_addon' => array(
                'file_path' => 'wt-woocommerce-proforma-addon/wt-woocommerce-proforma-addon.php',
                'logo' => $wf_admin_img_path.'/wt_pi_logo.png',
                'title' => __('WooCommerce Proforma Invoices', 'print-invoices-packing-slip-labels-for-woocommerce'),
                'page_link' => 'https://www.webtoffee.com/product/woocommerce-proforma-invoice/?utm_source=other_solution_page&utm_medium=free_plugin&utm_campaign=Proforma_Invoice',
                'features_list' => array(
                    __("Create proforma invoices automatically","print-invoices-packing-slip-labels-for-woocommerce"),
                    __("Pre-built proforma invoice layouts","print-invoices-packing-slip-labels-for-woocommerce"),
                    __("Easy invoice layout customization","print-invoices-packing-slip-labels-for-woocommerce"),
                    __("Attach proforma invoice PDF to order emails","print-invoices-packing-slip-labels-for-woocommerce"),
                    __("Allow customers to print invoices","print-invoices-packing-slip-labels-for-woocommerce"),
                    __("Set custom proforma invoice number","print-invoices-packing-slip-labels-for-woocommerce"),
                    __("Add additional product & order data fields","print-invoices-packing-slip-labels-for-woocommerce"),
                    __("Attach special notes with proforma invoices","print-invoices-packing-slip-labels-for-woocommerce"),
                    __("Attach transport & sales terms","print-invoices-packing-slip-labels-for-woocommerce"),
                    __("Multilingual support","print-invoices-packing-slip-labels-for-woocommerce"),
                ),
            ),
            'wt_qr_addon' => array(
                'file_path' => 'qrcode-addon-for-woocommerce-pdf-invoices/qrcode-addon-for-woocommerce-pdf-invoices.php',
                'logo' => $wf_admin_img_path.'/wt_qrcode_logo.png',
                'title' => __("QR Code Addon for WooCommerce PDF Invoices","print-invoices-packing-slip-labels-for-woocommerce"),
                'page_link' => 'https://www.webtoffee.com/product/qr-code-addon-for-woocommerce-pdf-invoices/?utm_source=free_plugin_addon_page&utm_medium=PDF_invoice_pro&utm_campaign=QR_Code_Addon&utm_content='.WF_PKLIST_VERSION,
                'features_list' => array(
                    __("Assign QR codes to all generated invoices","print-invoices-packing-slip-labels-for-woocommerce"),
                    __("Create QR code that reads order or invoice number","print-invoices-packing-slip-labels-for-woocommerce"),
                    __("Add custom data to invoices","print-invoices-packing-slip-labels-for-woocommerce"),
                    __("Compatible with WooCommerce PDF Invoice, Packing Slip & Credit Note (Premium)","print-invoices-packing-slip-labels-for-woocommerce"),
                    __("Compatible with WooCommerce PDF Invoices, Packing Slips, Delivery Notes, and Shipping Labels (Free)","print-invoices-packing-slip-labels-for-woocommerce"),
                ),
            ),
            'wt_remote_printnode' => array(
                'file_path' => 'wt-woocommerce-packing-list-printnode/wt-woocommerce-packing-list-printnode.php',
                'logo' => $wf_admin_img_path.'/wt_qrcode_logo.png',
                'title' => __("Remote Print add-on for WooCommerce PDF Invoices - PrintNode","print-invoices-packing-slip-labels-for-woocommerce"),
                'page_link' => 'https://www.webtoffee.com/product/remote-print-woocommerce-pdf-invoice-printnode/?utm_source=free_plugin_addon_page&utm_medium=PDF_invoice&utm_campaign=Remote_Print_Addon&utm_content='.WF_PKLIST_VERSION,
                'features_list' => array(
                    __("Offers cloud printing of invoice PDFs using PrintNode","print-invoices-packing-slip-labels-for-woocommerce"),
                    __("Print PDF invoices for WooCommerce","print-invoices-packing-slip-labels-for-woocommerce"),
                    __("Lightning-fast printing","print-invoices-packing-slip-labels-for-woocommerce"),
                    __("Supports automatic & manual printing","print-invoices-packing-slip-labels-for-woocommerce"),
                    __("Support for serial and USB scales","print-invoices-packing-slip-labels-for-woocommerce"),
                    __("Ensure security with base64 & URI printing","print-invoices-packing-slip-labels-for-woocommerce"),
                    __("Cross-platform compatibility","print-invoices-packing-slip-labels-for-woocommerce"),
                ),
            ),
            'wt_request_quote' => array(
                'file_path' => 'wt-woo-request-quote/wt-woo-request-quote.php',
                'logo'      => $wf_admin_img_path_os.'/request-quote.png',
                'title'     => __("WebToffee WooCommerce Request A Quote","print-invoices-packing-slip-labels-for-woocommerce"),
                'page_link' => 'https://www.webtoffee.com/product/woocommerce-request-a-quote/?utm_source=other_solution_page&utm_medium=free_plugin&utm_campaign=Request_Quote',
                'features_list' => array(
                    __("Add quote button to the product & shop pages","print-invoices-packing-slip-labels-for-woocommerce"),
                    __("Enable quotation request for selected products","print-invoices-packing-slip-labels-for-woocommerce"),
                    __("Automatically send quotes to users","print-invoices-packing-slip-labels-for-woocommerce"),
                    __("Disable guest users from asking for quote","print-invoices-packing-slip-labels-for-woocommerce"),
                    __("Hide prices and ‘add to cart’ button","print-invoices-packing-slip-labels-for-woocommerce"),
                    __("Automatic email alerts for admin & users","print-invoices-packing-slip-labels-for-woocommerce"),
                    __("Easy button and form customization","print-invoices-packing-slip-labels-for-woocommerce"),
                    __("Set quote expiry period","print-invoices-packing-slip-labels-for-woocommerce"),
                    __("Limit spams with reCAPTCHA","print-invoices-packing-slip-labels-for-woocommerce"),
                ),
            ),
            'wt_seq_no' => array(
                'file_path' => 'wt-woocommerce-sequential-order-numbers-pro/wt-advanced-order-number-pro.php',
                'logo'      => $wf_admin_img_path_os.'/Sequential-order-number-plugin.png',
                'title'     => __("Sequential Order Number for WooCommerce","print-invoices-packing-slip-labels-for-woocommerce"),
                'page_link' => 'https://www.webtoffee.com/product/woocommerce-sequential-order-numbers/?utm_source=other_solution_page&utm_medium=free_plugin&utm_campaign=Sequential_Order_Numbers',
                'features_list' => array(
                    __("Auto reset sequence per month/year etc","print-invoices-packing-slip-labels-for-woocommerce"),
                    __("Add a custom suffix for order numbers","print-invoices-packing-slip-labels-for-woocommerce"),
                    __("Date suffix in order numbers","print-invoices-packing-slip-labels-for-woocommerce"),
                    __("Custom sequence for free orders","print-invoices-packing-slip-labels-for-woocommerce"),
                    __("Increment sequence in custom series","print-invoices-packing-slip-labels-for-woocommerce"),
                    __("More order number templates","print-invoices-packing-slip-labels-for-woocommerce"),
                ),
            ),         
        ),
    ),
    'administration' => array(
        'domain_name' => __("Data Import & Export","print-invoices-packing-slip-labels-for-woocommerce"),
        'domain_caption' => __("The best-in-the-class import, export, and migration solutions for your WooCommerce data","print-invoices-packing-slip-labels-for-woocommerce"),
        'domain_logo' => $wf_admin_img_path.'/pro_addons/admin_cat_logo.png',
        'plugins' => array(
            'import_export_suite' => array(
                'file_path'     => '',
                'logo'     => $wf_admin_img_path_os.'/suite-1-plugin.png',
                'title'         => __('Import Export Suite for WooCommerce', 'print-invoices-packing-slip-labels-for-woocommerce'),
                'page_link'   => 'https://www.webtoffee.com/product/woocommerce-import-export-suite/?utm_source=other_solution_page&utm_medium=free_plugin&utm_campaign=Import_Export_Suite',
                'features_list' => array(
                    __("Import/export Products, Orders, Subscriptions, Coupons, Customers, WordPress Users, Categories & Tags, Reviews","print-invoices-packing-slip-labels-for-woocommerce"),
                    __("Supports Excel, XML, CSV, and TSV file formats","print-invoices-packing-slip-labels-for-woocommerce"),
                    __("Schedule automated import & export","print-invoices-packing-slip-labels-for-woocommerce"),
                    __("Import from URL, Google Sheets, FTP/SFTP","print-invoices-packing-slip-labels-for-woocommerce"),
                    __("Export to FTP/SFTP","print-invoices-packing-slip-labels-for-woocommerce"),
                    __("Import & export custom fields and values","print-invoices-packing-slip-labels-for-woocommerce"),
                    __("Advanced filters and customizations for import & export","print-invoices-packing-slip-labels-for-woocommerce"),
                    __("Add and update data while importing","print-invoices-packing-slip-labels-for-woocommerce"),
                    __("Maintains action history and debug logs","print-invoices-packing-slip-labels-for-woocommerce"),
                    __("Compatible with major 3rd-party plugins","print-invoices-packing-slip-labels-for-woocommerce"),                    
                ),
            ),
            'product_import_export_plugin' => array(
                'file_path'     => 'wt-import-export-for-woo-product/wt-import-export-for-woo-product.php',
                'logo'          => $wf_admin_img_path_os.'/product-import-export-plugin.png',
                'title'         => __('Product Import Export Plugin For WooCommerce', 'print-invoices-packing-slip-labels-for-woocommerce'),
                'page_link'     => 'https://www.webtoffee.com/product/product-import-export-woocommerce/?utm_source=other_solution_page&utm_medium=free_plugin&utm_campaign=Product_Import_Export',
                'features_list' => array(
                    __("Supports Excel, XML, CSV, and TSV file formats","print-invoices-packing-slip-labels-for-woocommerce"),
                    __("Schedule automated import and export","print-invoices-packing-slip-labels-for-woocommerce"),
                    __("Support for multiple product types","print-invoices-packing-slip-labels-for-woocommerce"),
                    __("Export product images in a separate zip file","print-invoices-packing-slip-labels-for-woocommerce"),
                    __("Import from URL, Google Sheets, FTP/SFTP","print-invoices-packing-slip-labels-for-woocommerce"),
                    __("Export to FTP/SFTP","print-invoices-packing-slip-labels-for-woocommerce"),
                    __("Advanced filters and customizations for import and export","print-invoices-packing-slip-labels-for-woocommerce"),
                    __("Add and update data while importing","print-invoices-packing-slip-labels-for-woocommerce"),
                    __("Maintains action history and debug logs","print-invoices-packing-slip-labels-for-woocommerce"),
                    __("Compatible with major 3rd-party plugins","print-invoices-packing-slip-labels-for-woocommerce"),
                ),
            ),
            'order_import_export_plugin' => array(
                'file_path'     => 'wt-import-export-for-woo-order/wt-import-export-for-woo-order.php',
                'logo'          => $wf_admin_img_path_os.'/order-import-export-plugin.png',
                'title'         => __('Order, Coupon, Subscription Export Import for WooCommerce', 'print-invoices-packing-slip-labels-for-woocommerce'),
                'page_link'     => 'https://www.webtoffee.com/product/order-import-export-plugin-for-woocommerce/?utm_source=other_solution_page&utm_medium=free_plugin&utm_campaign=Order_Import_Export',
                'features_list' => array(
                    __("Supports Excel, XML, CSV, and TSV file formats","print-invoices-packing-slip-labels-for-woocommerce"),
                    __("Schedule automated import & export","print-invoices-packing-slip-labels-for-woocommerce"),
                    __("Email customers on order status change","print-invoices-packing-slip-labels-for-woocommerce"),
                    __("Create users on order import","print-invoices-packing-slip-labels-for-woocommerce"),
                    __("Filter export by products, order status, email, date, etc","print-invoices-packing-slip-labels-for-woocommerce"),
                    __("Import from URL, Google Sheets, FTP/SFTP","print-invoices-packing-slip-labels-for-woocommerce"),
                    __("Export to FTP/SFTP","print-invoices-packing-slip-labels-for-woocommerce"),
                    __("Advanced filters and customizations for import & export","print-invoices-packing-slip-labels-for-woocommerce"),
                    __("Add & update data while importing","print-invoices-packing-slip-labels-for-woocommerce"),
                    __("Maintains action history and debug logs","print-invoices-packing-slip-labels-for-woocommerce"),
                    __("Compatible with major 3rd-party plugins","print-invoices-packing-slip-labels-for-woocommerce"),
                ),
            ),
            'user_import_export_plugin' => array(
                'file_path'     => 'wt-import-export-for-woo-user/wt-import-export-for-woo-user.php',
                'logo'          => $wf_admin_img_path_os.'/user-import-export-plugin.png',
                'title'         => __('WordPress Users & WooCommerce Customers Import Export', 'print-invoices-packing-slip-labels-for-woocommerce'),
                'page_link'     => 'https://www.webtoffee.com/product/wordpress-users-woocommerce-customers-import-export/?utm_source=other_solution_page&utm_medium=free_plugin&utm_campaign=User_Import_Export',
                'features_list' => array(
                    __("Supports Excel, XML, CSV, and TSV file formats","print-invoices-packing-slip-labels-for-woocommerce"),
                    __("Schedule automated import and export","print-invoices-packing-slip-labels-for-woocommerce"),
                    __("Customize and send emails to new users on import","print-invoices-packing-slip-labels-for-woocommerce"),
                    __("Retain user passwords on import/export","print-invoices-packing-slip-labels-for-woocommerce"),
                    __("Export and import custom fields and third-party plugin fields","print-invoices-packing-slip-labels-for-woocommerce"),
                    __("Filter by user role, email, date, etc","print-invoices-packing-slip-labels-for-woocommerce"),
                    __("Import from URL, Google Sheets, FTP/SFTP","print-invoices-packing-slip-labels-for-woocommerce"),
                    __("Export to FTP/SFTP","print-invoices-packing-slip-labels-for-woocommerce"),
                    __("Advanced filters and customizations for import & export","print-invoices-packing-slip-labels-for-woocommerce"),
                    __("Add & update data while importing","print-invoices-packing-slip-labels-for-woocommerce"),
                    __("Maintains action history and debug logs","print-invoices-packing-slip-labels-for-woocommerce"),
                    __("Compatible with major 3rd-party plugins","print-invoices-packing-slip-labels-for-woocommerce"),
                ),
            ),
            'product_feed_sync' => array(
                'file_path'     => 'webtoffee-product-feed-pro/webtoffee-product-feed-pro.php',
                'logo'          => $wf_admin_img_path_os.'/product-feed-sync.png',
                'title'         => __('WebToffee WooCommerce Product Feed & Sync Manager', 'print-invoices-packing-slip-labels-for-woocommerce'),
                'page_link'     => 'https://www.webtoffee.com/product/product-catalog-sync-for-facebook/?utm_source=other_solution_page&utm_medium=free_plugin&utm_campaign=WooCommerce_Product_Feed',
                'features_list' => array(
                    __("Generate WooCommerce product feeds for Google Shopping, Facebook Shop, and Instagram Shop","print-invoices-packing-slip-labels-for-woocommerce"),
                    __("Sync WooCommerce products to Facebook catalog","print-invoices-packing-slip-labels-for-woocommerce"),
                    __("Additional feed intervals (30 minutes, 6 hours, 12 hours)","print-invoices-packing-slip-labels-for-woocommerce"),
                    __("Support for additional fields that can be added to the feed","print-invoices-packing-slip-labels-for-woocommerce"),
                    __("WPML multilingual and multicurrency support ","print-invoices-packing-slip-labels-for-woocommerce"),
                    __("Google local product inventory feed","print-invoices-packing-slip-labels-for-woocommerce"),
                    __("Exclude specific products","print-invoices-packing-slip-labels-for-woocommerce"),
                    __("Include or exclude specific categories","print-invoices-packing-slip-labels-for-woocommerce"),
                    __("Exclude out-of-stock products","print-invoices-packing-slip-labels-for-woocommerce"),
                    __("Filter products based on product type","print-invoices-packing-slip-labels-for-woocommerce"),
                    __("Map categories on product level","print-invoices-packing-slip-labels-for-woocommerce"),
                    
                ),
            ),
            'backup_and_migration_plugin' => array(
                'file_path'     => 'wp-migration-duplicator-pro/wp-migration-duplicator-pro.php',
                'logo'          => $wf_admin_img_path_os.'/WordPress-backup-and-migration-plugin.png',
                'title'         => __('WordPress Backup and Migration', 'print-invoices-packing-slip-labels-for-woocommerce'),
                'page_link'     => 'https://www.webtoffee.com/product/wordpress-backup-and-migration/?utm_source=other_solution_page&utm_medium=free_plugin&utm_campaign=WordPress_Backup',
                'features_list' => array(
                    __("One-click backup and restore","print-invoices-packing-slip-labels-for-woocommerce"),
                    __("Multiple storage locations","print-invoices-packing-slip-labels-for-woocommerce"),
                    __("URL import supported","print-invoices-packing-slip-labels-for-woocommerce"),
                    __("Email notifications support","print-invoices-packing-slip-labels-for-woocommerce"),
                    __("Multiple file formats supported","print-invoices-packing-slip-labels-for-woocommerce"),
                    __("Auto delete backups","print-invoices-packing-slip-labels-for-woocommerce"),
                    __("Exclude specific DB tables","print-invoices-packing-slip-labels-for-woocommerce"),
                ),
            ),
        ),
    ),
    'promotion' => array(
        'domain_name' => __("E-commerce Promotions","print-invoices-packing-slip-labels-for-woocommerce"),
        'domain_caption' => __("Create and run successful promotional campaigns with the best tools for WooCommerce","print-invoices-packing-slip-labels-for-woocommerce"),
        'domain_logo' => $wf_admin_img_path.'/pro_addons/promotion_cat_logo.png',
        'plugins' => array(
            'diplay_discount'   => array(
                'file_path'     => 'wt-display-discounts-for-woocommerce/wt_display_discounts_for_woocommerce.php',
                'logo'          => $wf_admin_img_path_os.'/display-discounts.png',
                'title'         => __('Display Discounts for WooCommerce', 'print-invoices-packing-slip-labels-for-woocommerce'),
                'page_link'     => 'https://www.webtoffee.com/product/display-woocommerce-discounts/?utm_source=other_solution_page&utm_medium=free_plugin&utm_campaign=Display_Discounts',
                'features_list' => array(
                    __("Display available coupons on the product pages","print-invoices-packing-slip-labels-for-woocommerce"),
                    __("Customize the coupon template","print-invoices-packing-slip-labels-for-woocommerce"),
                    __("Show countdown timers for time-limited coupons","print-invoices-packing-slip-labels-for-woocommerce"),
                    __("Show restriction info within the coupon","print-invoices-packing-slip-labels-for-woocommerce"),
                    __("Limit the number of coupons to display on a page","print-invoices-packing-slip-labels-for-woocommerce"),
                    __("Hide discount display section from guest users","print-invoices-packing-slip-labels-for-woocommerce"),
                    __("Hide coupons without restrictions","print-invoices-packing-slip-labels-for-woocommerce"),
                    __("Adjust the discounts section location","print-invoices-packing-slip-labels-for-woocommerce"),                    
                ),    
            ),
            'giftcards_plugin'  => array(
                'file_path'     => 'wt-woocommerce-gift-cards/wt-woocommerce-gift-cards.php',
                'logo'          => $wf_admin_img_path_os.'/giftcards_plugin.png',
                'title'         => __('WebToffee WooCommerce Gift Cards', 'print-invoices-packing-slip-labels-for-woocommerce'),
                'page_link'     => 'https://www.webtoffee.com/product/woocommerce-gift-cards/?utm_source=other_solution_page&utm_medium=free_plugin&utm_campaign=WooCommerce_Gift_Cards',
                'features_list' => array(
                    __("Create unlimited gift cards","print-invoices-packing-slip-labels-for-woocommerce"),
                    __("Email gift cards to customers","print-invoices-packing-slip-labels-for-woocommerce"),
                    __("Provide refunds to store credit","print-invoices-packing-slip-labels-for-woocommerce"),
                    __("20+ predefined gift card templates","print-invoices-packing-slip-labels-for-woocommerce"),
                    __("Category wise template listing","print-invoices-packing-slip-labels-for-woocommerce"),
                    __("Add custom templates for gift cards","print-invoices-packing-slip-labels-for-woocommerce"),
                    __("Generate gift cards based on order status","print-invoices-packing-slip-labels-for-woocommerce"),
                    __("Manage user credit balance","print-invoices-packing-slip-labels-for-woocommerce"),
                    __("Fixed and custom gift card amounts","print-invoices-packing-slip-labels-for-woocommerce"),
                    __("Add usage restrictions for gift cards","print-invoices-packing-slip-labels-for-woocommerce"),
                ),
            ),
            'fbt_plugins'   => array(
                'file_path'     => 'wt-frequently-bought-together/wt-frequently-bought-together.php',
                'logo'          => $wf_admin_img_path_os.'/fbt_plugin.png',
                'title'         => __('Frequently Bought Together for WooCommerce', 'print-invoices-packing-slip-labels-for-woocommerce'),
                'page_link'     => 'https://www.webtoffee.com/product/woocommerce-frequently-bought-together/?utm_source=other_solution_page&utm_medium=free_plugin&utm_campaign=Frequently_Bought_Together',
                'features_list' => array(
                    __("Automatically generate suggestions based on order history","print-invoices-packing-slip-labels-for-woocommerce"),
                    __("Display recommended products on the product pages","print-invoices-packing-slip-labels-for-woocommerce"),
                    __("Quick setup page to add & edit recommendations","print-invoices-packing-slip-labels-for-woocommerce"),
                    __("Multiple product recommendation layouts","print-invoices-packing-slip-labels-for-woocommerce"),
                    __("Set up discounts on the recommended product bundle","print-invoices-packing-slip-labels-for-woocommerce"),
                    __("Manually create a bought-together list","print-invoices-packing-slip-labels-for-woocommerce"),
                    __("Use upsells, cross-sells, & related products as frequently bought products","print-invoices-packing-slip-labels-for-woocommerce"),
                    __("Customize the title, button, and label texts","print-invoices-packing-slip-labels-for-woocommerce"),
                    __("Customize the display of the recommended products","print-invoices-packing-slip-labels-for-woocommerce"),
                ),
            ),
            'smart_coupons_plugin' => array(
                'file_path'     => 'wt-smart-coupon-pro/wt-smart-coupon-pro.php',
                'logo'          => $wf_admin_img_path_os.'/smart-coupons-plugin.png',
                'title'         => __('Smart Coupons for WooCommerce', 'print-invoices-packing-slip-labels-for-woocommerce'),
                'page_link'     => 'https://www.webtoffee.com/product/smart-coupons-for-woocommerce/?utm_source=other_solution_page&utm_medium=free_plugin&utm_campaign=smart_coupons',
                'features_list' => array(
                    __("Advanced BOGO Coupons","print-invoices-packing-slip-labels-for-woocommerce"),
                    __("Offer store credits","print-invoices-packing-slip-labels-for-woocommerce"),
                    __("Create attractive gift cards ","print-invoices-packing-slip-labels-for-woocommerce"),
                    __("Give away product coupons","print-invoices-packing-slip-labels-for-woocommerce"),
                    __("Coupons based on past purchases","print-invoices-packing-slip-labels-for-woocommerce"),
                    __("Restrict coupons by country","print-invoices-packing-slip-labels-for-woocommerce"),
                    __("Create and offer sign-up discount coupons","print-invoices-packing-slip-labels-for-woocommerce"),
                    __("Cart abandonment coupons","print-invoices-packing-slip-labels-for-woocommerce"),
                    __("Customizable countdown sales banner","print-invoices-packing-slip-labels-for-woocommerce"),
                    __("Bulk generate coupons","print-invoices-packing-slip-labels-for-woocommerce"),
                    __("Import and export coupons","print-invoices-packing-slip-labels-for-woocommerce"),
                    __("Coupon embeds","print-invoices-packing-slip-labels-for-woocommerce"),
                    __("Allow coupon combinations","print-invoices-packing-slip-labels-for-woocommerce"),
                ),
            ),
            'url_coupons_plugin' => array(
                'file_path'     => 'wt-woocommerce-gift-cards/wt-woocommerce-gift-cards.php',
                'logo'          => $wf_admin_img_path_os.'/url-coupons-plugin.png',
                'title'         => __('URL Coupons for WooCommerce', 'print-invoices-packing-slip-labels-for-woocommerce'),
                'page_link'     => 'https://www.webtoffee.com/product/url-coupons-for-woocommerce/?utm_source=other_solution_page&utm_medium=free_plugin&utm_campaign=URL_Coupons',
                'features_list' => array(
                    __("Generate custom coupon URLs","print-invoices-packing-slip-labels-for-woocommerce"),
                    __("Set up a redirect page","print-invoices-packing-slip-labels-for-woocommerce"),
                    __("Automatically add products","print-invoices-packing-slip-labels-for-woocommerce"),
                    __("Create QR code coupons","print-invoices-packing-slip-labels-for-woocommerce"),                    
                ),
            ),
            'best_sellers_plugin' => array(
                'file_path'     => 'wt-woocommerce-best-seller/wt-woocommerce-best-sellers.php',
                'logo'          => $wf_admin_img_path_os.'/bestsellers_plugin.png',
                'title'         => __('WebToffee WooCommerce Best Sellers', 'print-invoices-packing-slip-labels-for-woocommerce'),
                'page_link'     => 'https://www.webtoffee.com/product/woocommerce-best-sellers/?utm_source=other_solution_page&utm_medium=free_plugin&utm_campaign=WooCommerce_Best_Sellers',
                'features_list' => array(
                    __("Create a best seller page for displaying best selling products","print-invoices-packing-slip-labels-for-woocommerce"),
                    __("Add best seller labels to WooCommerce products","print-invoices-packing-slip-labels-for-woocommerce"),
                    __("Rank products based on sales","print-invoices-packing-slip-labels-for-woocommerce"),
                    __("Supports simple and variable products","print-invoices-packing-slip-labels-for-woocommerce"),
                    __("Create a best seller slider on store pages","print-invoices-packing-slip-labels-for-woocommerce"),
                    __("Add a custom best seller seal","print-invoices-packing-slip-labels-for-woocommerce"),
                    __("Customize slider view for WooCommerce best sellers","print-invoices-packing-slip-labels-for-woocommerce"),
                    __("Set product limit for best sellers","print-invoices-packing-slip-labels-for-woocommerce"),
                ),
            ),
        ),
    ),
    'payment'   => array(
        'domain_name'   => __("Payment & subscription","print-invoices-packing-slip-labels-for-woocommerce"),
        'domain_caption' => __("The most popular payment gateways and subscription solutions to scale your business","print-invoices-packing-slip-labels-for-woocommerce"),
        'domain_logo' => $wf_admin_img_path.'/pro_addons/payment_cat_logo.png',
        'plugins' => array(
            'stripe_paymet_gateway_plugin' => array(
                'file_path'     => 'eh-stripe-payment-gateway/stripe-payment-gateway.php',
                'title'         => __('WooCommerce Stripe Payment Gateway', 'print-invoices-packing-slip-labels-for-woocommerce'),
                'logo'          => $wf_admin_img_path_os.'/stripe-plugin.png',
                'page_link'     => 'https://www.webtoffee.com/product/woocommerce-stripe-payment-gateway/?utm_source=other_solution_page&utm_medium=free_plugin&utm_campaign=Stripe',
                'features_list' => array(
                    __("Add 20+ payment methods","print-invoices-packing-slip-labels-for-woocommerce"),
                    __("Activates Stripe checkout","print-invoices-packing-slip-labels-for-woocommerce"),
                    __("Secured payments with SCA and 3D secure","print-invoices-packing-slip-labels-for-woocommerce"),
                    __("Supports recurring payments","print-invoices-packing-slip-labels-for-woocommerce"),
                    __("Compatible with WPML","print-invoices-packing-slip-labels-for-woocommerce"),
                    __("Log all Stripe transactions","print-invoices-packing-slip-labels-for-woocommerce"),
                    __("Monitor payments using Stripe dashboard","print-invoices-packing-slip-labels-for-woocommerce"),                    
                ),
            ),
            'paypal_express_checkout_plugin' => array(
                'file_path'     => 'eh-paypal-express-checkout /eh-paypal-express-checkout.php',
                'title'         => __('PayPal Express Checkout Payment Gateway for WooCommerce', 'print-invoices-packing-slip-labels-for-woocommerce'),
                'logo'          => $wf_admin_img_path_os.'/wt-paypal-plugin.png',
                'page_link'     => 'https://www.webtoffee.com/product/paypal-express-checkout-gateway-for-woocommerce/?utm_source=other_solution_page&utm_medium=free_plugin&utm_campaign=Paypal',
                'features_list' => array(
                    __("Adds PayPal Smart Button Checkout option","print-invoices-packing-slip-labels-for-woocommerce"),
                    __("Accepts payment using multiple Alternative Payment Methods (APM)","print-invoices-packing-slip-labels-for-woocommerce"),
                    __("Adds Express PayPal Checkout Option on the product page and Mini-cart for faster checkout","print-invoices-packing-slip-labels-for-woocommerce"),
                    __("Capture the authorized payment later","print-invoices-packing-slip-labels-for-woocommerce"),
                    __("Partial and Full Refund of the order amount","print-invoices-packing-slip-labels-for-woocommerce"),
                    __("Lots of customization options like button style, position, etc","print-invoices-packing-slip-labels-for-woocommerce"),
                    __("Option to enable in-context checkout","print-invoices-packing-slip-labels-for-woocommerce"),
                    __("Supports WooCommerce Subscriptions for Express buttons","print-invoices-packing-slip-labels-for-woocommerce"),
                    __("Allows guest checkout","print-invoices-packing-slip-labels-for-woocommerce"),
                    __("Option to set up a specific PayPal locale","print-invoices-packing-slip-labels-for-woocommerce"),
                    __("Shortcode support for the Paypal Express button","print-invoices-packing-slip-labels-for-woocommerce"),
                    __("Timely compatibility updates and bug fixes","print-invoices-packing-slip-labels-for-woocommerce"),
                ),
            ),
            'subscriptions_for_woocommerce_plugin' => array(
                'file_path'     => 'xa-woocommerce-subscriptions/xa-woocommerce-subscriptions.php',
                'title'         => __('Subscriptions for WooCommerce', 'print-invoices-packing-slip-labels-for-woocommerce'),
                'logo'          => $wf_admin_img_path_os.'/subscription-plugin.png',
                'page_link'     => 'https://www.webtoffee.com/product/woocommerce-subscriptions/?utm_source=other_solution_page&utm_medium=free_plugin&utm_campaign=Subscriptions',
                'features_list' => array(
                    __("Create simple & variable subscriptions","print-invoices-packing-slip-labels-for-woocommerce"),
                    __("Synchronize subscription renewal","print-invoices-packing-slip-labels-for-woocommerce"),
                    __("Pro-rate charges till first renewal","print-invoices-packing-slip-labels-for-woocommerce"),
                    __("Set free trial and sign-up fee","print-invoices-packing-slip-labels-for-woocommerce"),
                    __("Send automated emails notifications","print-invoices-packing-slip-labels-for-woocommerce"),
                    __("Supports recurring discounts","print-invoices-packing-slip-labels-for-woocommerce"),
                    __("Renewal interval & expiry customizations","print-invoices-packing-slip-labels-for-woocommerce"),
                ),
            ),
        ),
    ),
    'privacy' => array(
        'domain_name' => __("Privacy compliance","print-invoices-packing-slip-labels-for-woocommerce"),
        'domain_caption' => __("Get Help with Ensuring Compliance to Major Privacy Laws for Your WordPress Website - GDPR, CCPA, LGPD, CNIL, and More.","print-invoices-packing-slip-labels-for-woocommerce"),
        'domain_logo' => $wf_admin_img_path.'/pro_addons/privacy_cat_logo.png',
        'plugins' => array(
            'diplay_discount'   => array(
                'file_path'     => 'webtoffee-gdpr-cookie-consent/cookie-law-info.php',
                'logo'          => $wf_admin_img_path_os.'/gdpr-cookie-concent-plugin.png',
                'title'         => __('GDPR Cookie Consent Plugin (CCPA Ready)', 'print-invoices-packing-slip-labels-for-woocommerce'),
                'page_link'     => 'https://www.webtoffee.com/product/gdpr-cookie-consent/?utm_source=other_solution_page&utm_medium=free_plugin&utm_campaign=GDPR',
                'features_list' => array(
                    __("Assits in GDPR (RGPD, DSVGO), LGPD, CNIL, POPIA, and CCPA","print-invoices-packing-slip-labels-for-woocommerce"),
                    __("Create a cookie consent banner","print-invoices-packing-slip-labels-for-woocommerce"),
                    __("Scan and list cookies","print-invoices-packing-slip-labels-for-woocommerce"),
                    __("Automatically block cookies/script","print-invoices-packing-slip-labels-for-woocommerce"),
                    __("Customize cookie banner","print-invoices-packing-slip-labels-for-woocommerce"),
                    __("Create cookie policy","print-invoices-packing-slip-labels-for-woocommerce"),
                    __("User consent logging","print-invoices-packing-slip-labels-for-woocommerce"),
                    __("Explicit/Implicit consent","print-invoices-packing-slip-labels-for-woocommerce"),
                    __("Location based exclusion for banner","print-invoices-packing-slip-labels-for-woocommerce"),
                    __("Granular consent based on cookie categories","print-invoices-packing-slip-labels-for-woocommerce"),              
                ),    
            ),
        ),
    ),
);
?>