<?php
if ( ! defined( 'WPINC' ) ) {
    die;
}
$pro_addons_list_details_addons_page = array(
	'wt_ipc_addon' => array(
	    'file_path' => 'wt-woocommerce-invoice-addon/wt-woocommerce-invoice-addon.php',
	    'logo' => $wf_admin_img_path.'/wt_ipc_logo.png',
	    'title' => __("WooCommerce PDF Invoices, Packing Slips and Credit Notes plugin","print-invoices-packing-slip-labels-for-woocommerce"),
	    'page_link_ms' => 'https://www.webtoffee.com/product/woocommerce-pdf-invoices-packing-slips/?utm_source=free_plugin_sidebar&utm_medium=pdf_basic&utm_campaign=PDF_invoice&utm_content='.WF_PKLIST_VERSION,
	    'page_link_fp' => 'https://www.webtoffee.com/product/woocommerce-pdf-invoices-packing-slips/?utm_source=free_plugin_comparison&utm_medium=pdf_basic&utm_campaign=PDF_invoice&utm_content='.WF_PKLIST_VERSION,
	    'page_link' => 'https://www.webtoffee.com/product/woocommerce-pdf-invoices-packing-slips/?utm_source=free_plugin_addon_page&utm_medium=pdf_basic&utm_campaign=PDF_invoice&utm_content='.WF_PKLIST_VERSION,
	    'features_list' => array(
	        __("Auto-generate invoices, packing slips, and credit notes","print-invoices-packing-slip-labels-for-woocommerce"),
	        __("Show payment link on invoice","print-invoices-packing-slip-labels-for-woocommerce"),
	        __("Add ‘Pay Later’ option at checkout","print-invoices-packing-slip-labels-for-woocommerce"),
	        __("Attach documents to selected order status emails","print-invoices-packing-slip-labels-for-woocommerce"),
	        __("Enable customers to print invoices & packing slips","print-invoices-packing-slip-labels-for-woocommerce"),
	        __("Customize document layout & properties","print-invoices-packing-slip-labels-for-woocommerce"),
	        __("Show product variation data","print-invoices-packing-slip-labels-for-woocommerce"),
	        __("Add custom data to documents","print-invoices-packing-slip-labels-for-woocommerce"),
	        __("Multiple display options for bundle products","print-invoices-packing-slip-labels-for-woocommerce"),
	        __("Group products by ‘Category’","print-invoices-packing-slip-labels-for-woocommerce"),
	        __("Verified compatibility with major plugins","print-invoices-packing-slip-labels-for-woocommerce"),
	        __("Multilingual support","print-invoices-packing-slip-labels-for-woocommerce"),
	    ),
	),
	'wt_sdd_addon' => array(
	    'file_path' => 'wt-woocommerce-shippinglabel-addon/wt-woocommerce-shippinglabel-addon.php',
	    'logo' => $wf_admin_img_path.'/wt_sdd_logo.png',
	    'title' => __("WooCommerce Shipping labels, Dispatch labels and Delivery Notes plugin","print-invoices-packing-slip-labels-for-woocommerce"),
	    'page_link_ms' => 'https://www.webtoffee.com/product/woocommerce-shipping-labels-delivery-notes/?utm_source=free_plugin_sidebar&utm_medium=pdf_basic&utm_campaign=Shipping_Label&utm_content='.WF_PKLIST_VERSION,
	    'page_link_fp' => 'https://www.webtoffee.com/product/woocommerce-shipping-labels-delivery-notes/?utm_source=free_plugin_comparison&utm_medium=pdf_basic&utm_campaign=Shipping_Label&utm_content='.WF_PKLIST_VERSION,
	    'page_link' => 'https://www.webtoffee.com/product/woocommerce-shipping-labels-delivery-notes/?utm_source=free_plugin_addon_page&utm_medium=pdf_basic&utm_campaign=Shipping_Label&utm_content='.WF_PKLIST_VERSION,
	    'features_list' => array(
	        __("Create delivery notes, shipping & dispatch labels","print-invoices-packing-slip-labels-for-woocommerce"),
	        __("Enable customers to print the documents from order emails","print-invoices-packing-slip-labels-for-woocommerce"), 
	        __("Customize shipping label size","print-invoices-packing-slip-labels-for-woocommerce"),
	        __("Add multiple shipping labels on one page","print-invoices-packing-slip-labels-for-woocommerce"),
	        __("Show product variation data","print-invoices-packing-slip-labels-for-woocommerce"), 
	        __("Add extra product & order data fields","print-invoices-packing-slip-labels-for-woocommerce"),
	        __("Pre-built layouts & customizable templates","print-invoices-packing-slip-labels-for-woocommerce"), 
	        __("Group products by ‘Category’","print-invoices-packing-slip-labels-for-woocommerce"),
	        __("Sort products based on Name or SKU","print-invoices-packing-slip-labels-for-woocommerce"),
	        __("Multilingual support","print-invoices-packing-slip-labels-for-woocommerce"),
	    ),
	),
	'wt_pl_addon' => array(
	    'file_path' => 'wt-woocommerce-picklist-addon/wt-woocommerce-picklist-addon.php',
	    'logo' => $wf_admin_img_path.'/wt_pl_logo.png',
	    'title' => __("WooCommerce Picklists plugin","print-invoices-packing-slip-labels-for-woocommerce"),
	    'page_link_ms' => 'https://www.webtoffee.com/product/woocommerce-picklist/?utm_source=free_plugin_sidebar&utm_medium=pdf_basic&utm_campaign=Picklist&utm_content='.WF_PKLIST_VERSION,
	    'page_link_fp' => 'https://www.webtoffee.com/product/woocommerce-picklist/?utm_source=free_plugin_comparison&utm_medium=pdf_basic&utm_campaign=Picklist&utm_content='.WF_PKLIST_VERSION,
	    'page_link' => 'https://www.webtoffee.com/product/woocommerce-picklist/?utm_source=free_plugin_addon_page&utm_medium=pdf_basic&utm_campaign=Picklist&utm_content='.WF_PKLIST_VERSION,
	    'features_list' => array(
	        __("Bulk print picklists from the admin order page","print-invoices-packing-slip-labels-for-woocommerce"),
	        __("Automatically email picklists based on order status","print-invoices-packing-slip-labels-for-woocommerce"),
	        __("Create or customize picklist templates","print-invoices-packing-slip-labels-for-woocommerce"),
	        __("Show product variation data","print-invoices-packing-slip-labels-for-woocommerce"),
	        __("Group products in picklist by order/category","print-invoices-packing-slip-labels-for-woocommerce"), 
	        __("Add product meta fields & attributes","print-invoices-packing-slip-labels-for-woocommerce"), 
	        __("Exclude virtual products from picklists","print-invoices-packing-slip-labels-for-woocommerce"),
	        __("Multilingual support","print-invoices-packing-slip-labels-for-woocommerce"),
	    ),
	),
	'wt_pi_addon' => array(
	    'file_path' => 'wt-woocommerce-proforma-addon/wt-woocommerce-proforma-addon.php',
	    'logo' => $wf_admin_img_path.'/wt_pi_logo.png',
	    'title' => __("WooCommerce Proforma Invoices plugin","print-invoices-packing-slip-labels-for-woocommerce"),
	    'page_link_ms'=>'https://www.webtoffee.com/product/woocommerce-proforma-invoice/?utm_source=free_plugin_sidebar&utm_medium=pdf_basic&utm_campaign=Proforma_Invoice&utm_content='.WF_PKLIST_VERSION,
	    'page_link_fp' => 'https://www.webtoffee.com/product/woocommerce-proforma-invoice/?utm_source=free_plugin_comparison&utm_medium=pdf_basic&utm_campaign=Proforma_Invoice&utm_content='.WF_PKLIST_VERSION,
	    'page_link' => 'https://www.webtoffee.com/product/woocommerce-proforma-invoice/?utm_source=free_plugin_addon_page&utm_medium=pdf_basic&utm_campaign=Proforma_Invoice&utm_content='.WF_PKLIST_VERSION,
	    'features_list' => array(
	        __("Create proforma invoices automatically","print-invoices-packing-slip-labels-for-woocommerce"),  
	        __("Pre-built proforma invoice layouts","print-invoices-packing-slip-labels-for-woocommerce"),
	        __("Easy invoice layout customization","print-invoices-packing-slip-labels-for-woocommerce"),
	        __("Attach proforma invoice PDF to order emails","print-invoices-packing-slip-labels-for-woocommerce"), 
	        __("Allow customers to print invoices","print-invoices-packing-slip-labels-for-woocommerce"), 
	        __("Set custom proforma invoice number","print-invoices-packing-slip-labels-for-woocommerce"), 
	        __("Add additional product & order data fields","print-invoices-packing-slip-labels-for-woocommerce"), 
	        __("Attach special notes with proforma invoices","print-invoices-packing-slip-labels-for-woocommerce"),
	        __("Attach transport & sales terms","print-invoices-packing-slip-labels-for-woocommerce"), 
	        __("Multilingual support","print-invoices-packing-slip-labels-for-woocommerce"),
	    ),
	),
	'wt_al_addon' => array(
	    'file_path' => 'wt-woocommerce-addresslabel-addon/wt-woocommerce-addresslabel-addon.php',
	    'logo' => $wf_admin_img_path.'/wt_al_logo.png',
	    'title' => __("WooCommerce Address Labels plugin","print-invoices-packing-slip-labels-for-woocommerce"),
	    'page_link_ms' => 'https://www.webtoffee.com/product/woocommerce-address-label/?utm_source=free_plugin_sidebar&utm_medium=pdf_basic&utm_campaign=Address_Label&utm_content='.WF_PKLIST_VERSION,
	    'page_link_fp' => 'https://www.webtoffee.com/product/woocommerce-address-label/?utm_source=free_plugin_comparison&utm_medium=pdf_basic&utm_campaign=Address_Label&utm_content='.WF_PKLIST_VERSION,
	    'page_link' => 'https://www.webtoffee.com/product/woocommerce-address-label/?utm_source=free_plugin_addon_page&utm_medium=pdf_basic&utm_campaign=Address_Label&utm_content='.WF_PKLIST_VERSION,
	    'features_list' => array(
	        __("Generate Shipping Address labels","print-invoices-packing-slip-labels-for-woocommerce"),
	        __("Generate Billing Address labels","print-invoices-packing-slip-labels-for-woocommerce"),
	        __("Generate From Address labels","print-invoices-packing-slip-labels-for-woocommerce"),
	        __("Generate Return Address labels","print-invoices-packing-slip-labels-for-woocommerce"), 
	        __("Customize label sizes","print-invoices-packing-slip-labels-for-woocommerce"),
	        __("Bulk print address labels","print-invoices-packing-slip-labels-for-woocommerce"), 
	        __("Built-in label templates","print-invoices-packing-slip-labels-for-woocommerce"),
	        __("Change address label layout","print-invoices-packing-slip-labels-for-woocommerce"),
	        __("Customize layout elements & properties","print-invoices-packing-slip-labels-for-woocommerce"),
	        __("Multilingual support","print-invoices-packing-slip-labels-for-woocommerce"),
	    ),
	),
	'wt_qr_addon' => array(
	    'file_path' => 'qrcode-addon-for-woocommerce-pdf-invoices/qrcode-addon-for-woocommerce-pdf-invoices.php',
	    'logo' => $wf_admin_img_path.'/wt_qrcode_logo.png',
	    'title' => __("QR Code Addon for WooCommerce PDF Invoices","print-invoices-packing-slip-labels-for-woocommerce"),
	    'page_link' => 'https://www.webtoffee.com/product/qr-code-addon-for-woocommerce-pdf-invoices/?utm_source=free_plugin_addon_page&utm_medium=PDF_invoice_pro&utm_campaign=QR_Code_Addon&utm_content='.WF_PKLIST_VERSION,
	    'page_link_ms' => 'https://www.webtoffee.com/product/qr-code-addon-for-woocommerce-pdf-invoices/?utm_source=free_plugin_addon_page&utm_medium=PDF_invoice_pro&utm_campaign=QR_Code_Addon&utm_content='.WF_PKLIST_VERSION,
	    'page_link_fp' => 'https://www.webtoffee.com/product/qr-code-addon-for-woocommerce-pdf-invoices/?utm_source=free_plugin_addon_page&utm_medium=PDF_invoice_pro&utm_campaign=QR_Code_Addon&utm_content='.WF_PKLIST_VERSION,
	    'features_list' => array(
	        __("Assign QR codes to all generated invoices","print-invoices-packing-slip-labels-for-woocommerce"),
	        __("Create QR code that reads order or invoice number","print-invoices-packing-slip-labels-for-woocommerce"), 
	        __("Add custom data to invoices","print-invoices-packing-slip-labels-for-woocommerce"), 
	        __("Compatible with WooCommerce PDF Invoice, Packing Slip & Credit Note (Pro)","print-invoices-packing-slip-labels-for-woocommerce"), 
	        __("Compatible with WooCommerce PDF Invoices, Packing Slips, Delivery Notes, and Shipping Labels (Free)","print-invoices-packing-slip-labels-for-woocommerce"),
	    ),
	),
);
?>